SET sql_safe_updates = 0;

SELECT MAX(SALARY) FROM hr.employees;
SELECT MIN(SALARY) FROM hr.employees;
SELECT MAX(SALARY) - MIN(SALARY) FROM hr.employees;
SELECT JOB_ID, SALARY FROM hr.employees ORDER BY SALARY DESC;
SELECT SUM(SALARY) FROM hr.employees;

SELECT MAX(SALARY) AS 'maior salario', 
MIN(SALARY) AS 'menor salario', 
SUM(SALARY) AS 'soma de todos os salarios', 
ROUND(AVG(SALARY), 2) AS 'media dos salarios'
FROM hr.employees;

SELECT COUNT(JOB_ID) FROM hr.employees WHERE JOB_ID = 'IT_PROG';
SELECT JOB_ID, SUM(SALARY) AS Soma FROM hr.employees GROUP BY JOB_ID ORDER BY Soma DESC;

SELECT JOB_ID, SUM(SALARY) AS Soma 
FROM hr.employees WHERE JOB_ID != 'IT_PROG' 
GROUP BY JOB_ID ORDER BY Soma DESC;

SELECT 
DEPARTMENT_ID, 
ROUND(AVG(SALARY), 2), 
COUNT(EMPLOYEE_ID) as employee_number 
FROM hr.employees 
GROUP BY DEPARTMENT_ID
HAVING employee_number > 10;

UPDATE hr.employees SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '515', '777') WHERE LEFT(PHONE_NUMBER, 3) = '515';
SELECT PHONE_NUMBER FROM hr.employees;

SELECT FIRST_NAME, CHAR_LENGTH(FIRST_NAME) AS tamanho FROM hr.employees HAVING tamanho >= 8;
SELECT EMPLOYEE_ID, FIRST_NAME, LEFT(HIRE_DATE, 4) FROM hr.employees;
SELECT EMPLOYEE_ID, FIRST_NAME, RIGHT(HIRE_DATE, 2) FROM hr.employees;
SELECT EMPLOYEE_ID, FIRST_NAME, SUBSTRING(HIRE_DATE, 6, 2) FROM hr.employees;
SELECT UCASE(FIRST_NAME) FROM hr.employees;
SELECT LAST_NAME, HIRE_DATE FROM hr.employees WHERE HIRE_DATE BETWEEN '1987-06-01' AND '1987-06-30';
SELECT FIRST_NAME, LAST_NAME, DATEDIFF(CURRENT_DATE(), HIRE_DATE) FROM hr.employees;
 
